Desktop Version Project
Have-Samuel/portfolio1 pull request #8
Opened 2022-01-18 19:00 UTC by Have-Samuel

In the Mobile Version Project we:

1. Made sure no Linter errors.
2. Documented the work professionally.
3. The Github workflow is proper
4. Added a contact form to the page.
5. And used media queries to reflect the responsiveness.

2022-01-18 20:15 UTC, moise10r requested changes
### Hi **@HAve-Samuel,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- GitHubFlow was correctly used.  ✔️   
- Professional README ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 20:15 UTC, moise10r commented on index.css
> +
- [ ] Please do not leave unused code as a comment in your codebase. this will make your code much noisy, It is always a good practice to keep your code clean from such comments.

2022-01-18 20:15 UTC, moise10r commented on index.html
> +         <!-- <h4 class="section3-heading">Proffesional Art Printing Data</h4>
- [ ] Please do not leave unused code as a comment in your codebase. this will make your code much noisy, It is always a good practice to keep your code clean from such comments.

2022-01-18 20:15 UTC, moise10r commented on index.css
> +  }
- [ ] I've noticed that your hamburger button from your mobile version no longer show the page menu when you make a click, kindly fix that

2022-01-18 20:15 UTC, moise10r commented on index.css
> +  }
- [ OPTIONAL] This is great using flexbox to layout your content, congrats 👏 , But we can still improve this code by using DRY (don't repeat yourself) but why? well, I realized that you have used the property `display: flex` at multiple places, please let's keep the code clean by extracting the property into a separate class that can be reused at multiple places, see the example below: 

- CSS file
```
.d-flex {
  display: flex;
}

.flex-center {
  flex-direction: column;
  justify-content: center;
}
```
- HTML file
```
<div class="d-flex flex-center">{your content}</div>
```

And remember you can do this for all the other properties that seem to be repeated multiple times, With this, I promise you'll be coding like a pro 😉

2022-01-18 20:15 UTC, moise10r commented on index.css
> +  }
- [ ] I think you can use `overflow: hidden` for your project,  your nested present some overflow inthe mobile version as well as the desktop version :point_down: 


> || mobile version | desktop version||
> |-|---------|----------|-|
> || ![mob](https://user-images.githubusercontent.com/57562869/150008366-f705fb99-097b-4e5a-93a9-3e07621f7f2c.png) | ![desk](https://user-images.githubusercontent.com/57562869/150008412-0c58cf81-4976-4be8-95bd-acefd988dad8.png)| 

- Please correct this also in other sections (my recent works, about me)

2022-01-18 20:15 UTC, moise10r commented on index.html
> +        </ul> -->
- [ ] Kindly, add the bar line, at the end of the about section  

- Figma Design:

![gg](https://user-images.githubusercontent.com/57562869/150011381-b81dfd6a-9df3-4795-a6e2-128dce768bca.png)

- Your Design:

![g3](https://user-images.githubusercontent.com/57562869/150011541-b25f9330-c266-4805-87b7-5e68fa605085.png)

2022-01-18 23:46 UTC, Have-Samuel commented on index.css
> +  }
I thought this was supposed to be added using Javascript, so i don't understand how you want me to do it, any suggestions are welcome.

2022-01-19 21:28 UTC, lily-coder approved these changes
Hi @Have-Samuel , 

Great job in implementing the changes requested by the previous reviewer. You can also consider the optional suggestions as they will make your code better. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/63964646/150216619-79e841d7-1fad-4434-841a-33f6863536b7.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-19 21:31 UTC, merged